### ISSUE TITLE
Unos telefona

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#16]
Komponenta:
DodavanjeAdministratora.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Prilikom dodavanja novog administratora nije uradjena korektna validacija podataka, odnosno, u slucaju upisivanja broja telefona nije uradjena nikakva validacija, pa tako ispravan unos moze biti samo jedan broj ili citav niz njih.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao administrator”. 
3. Unijeti validne podatke za username i password.
4. Izabrati na meniju Administratori opciju za dodavanje administratora.
5. Prilikom upisivanja telefona, polje nije validirano, dozvoljen je unos niza bilo kakvih brojeva,

**Comment by ToniMilicevic** [comment]
Sada je dozvoljen unos od 6 do 13 cifara kao broj telefona.
Commit
7be9cd20361a84b366af87023a6f55b79d6139a5
