### ISSUE TITLE
Pretraga administratora

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#17]
Komponenta:
PregledAdministratora.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Na formi za pregled administratora uradjena je validacija polja za unos vrijednosti pretrage samo u slucaju datuma, tj. jedino se u slucaju datuma javlja poruka o pogresnom unosu, dok se za sve ostale kategorije pretrage omogucuje unos bilo kakvih podataka. 

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao administrator” .
3. Unijeti validne podatke za username i password
4. Izabrati na meniju Administratori opciju za pregled administratora.
5. Prilikom upisivanja pogresnog formata imena ili bilo koje druge kategorije pretrage izuzev datuma nije uradjena nikakva validacija, dok se u slucaju unosa pogresnog formata datuma javlja poruka o tome.

**Comment by FarukLjuca** [comment]
Isti odgovor kao za Issue broj 19.
