### ISSUE TITLE
Pregled administratora

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#18]
Komponenta:
PregledAdministratora.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Tabela u kojoj se prikazuju administratori nije dovoljno rasirena, pa se tako podaci u nekim kolonama ne vide u potpunosti (kolone datum i email).
Prikaz rezultata:
![slika1](https://cloud.githubusercontent.com/assets/11391469/7839911/2ea3634a-0495-11e5-98e2-69d27bfb22fa.jpg)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao administrator”. 
3. Unijeti validne podatke za username i password.
4. Izabrati na meniju Administratori opciju za pregled administratora.

**Comment by FarukLjuca** [comment]
Isti odgovor kao na Issue broj 20.
