### ISSUE TITLE
Pretraga klijenata

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#19]
Isto kao #17 

Komponenta:
PregledKlijenata.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Na formi za pregled klijenata uradjena je validacija polja za unos vrijednosti pretrage samo u slucaju datuma, tj. jedino se u slucaju datuma javlja poruka o pogresnom unosu, dok se za sve ostale kategorije pretrage omogucuje unos bilo kakvih podataka.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Izabrati opciju “Registrovati se kao administrator” 
3. Unijeti validne podatke za username i password
4. Izabrati na meniju Klijenti opciju za pregled klijenata
5. Prilikom upisivanja pogresnog formata imena ili bilo koje druge kategorije izuzev datuma nije uradjena nikakva validacija,
dok se u slucaju unosa pogresnog formata datuma, javlja poruka o tome.

**Comment by FarukLjuca** [comment]
Poštovana kolegice,

Ne vidim razlog da se stavlja validacija na polje pretrage. Nema načina da se sigurnost sistema ugrozi ili da se sitem ošteti. Jedina stvar koju ćete postići pokušajem pretraživanja stringa ?_?_? jeste da nećete dobiti rezultate.

Za datum je druga priča, on ima format koji mora zadovoljiti inaće će pretraga željenog datuma biti neuspješna.

**Comment by CSharpQueen** [comment]
Nekonzistentnost, ili za sve kategorije ili nikako.
