### ISSUE TITLE
Pregled klijenata

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#20]
Isto kao #18 

Komponenta:
PregledKlijenata.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Tabela u kojoj se prikazuju klijenti nije dovoljno rasirena, pa se tako podaci u nekim kolonama ne vide u potpunosti (kolone datum i email).

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao administrator”.
3. Unijeti validne podatke za username i password.
4. Izabrati na meniju Klijenti opciju za pregled klijenata.

**Comment by FarukLjuca** [comment]
Poštovana kolegice,

Širina polja uvijek može biti premala, jer se na formi o kojoj govorimo može desiti da Klijent ima i dugu adresu i dug mail itd.

Rješenja koja su otvorena za korištenej su maksimizacija forme i promjena širine kolona (koju naravno nismo zabranili), kao na slici ispod.
http://prntscr.com/7a31xr

Mislim da "gatanje" kolika forma treba ne dolazi u obzir.

**Comment by CSharpQueen** [comment]
Kolona adresa nije ni navedena, vec datum, koji je uvijek istog formata.
