### ISSUE TITLE
Modifikacija ankete (buttoni)

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#22]
Komponenta:
ModifikacijaAnkete.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Prilikom pokretanja forme za modfikaciju ankete ne vidi se cijeli tekst na buttonima.
Prikaz rezultata:
![slikaa](https://cloud.githubusercontent.com/assets/11391469/7840262/cfd0248c-0496-11e5-8fa5-8da0a5a07c85.jpg)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao administrator”.
3. Unijeti validne podatke za username i password.
4. Izabrati na meniju Ankete opciju za manipulaciju. Na prikazanoj formi oznaciti neku od anketa, te
klikom na dugme izabrati opciju za njeno modifikovanje.

**Comment by akadrispahic** [comment]
Ispravljeno.
