### ISSUE TITLE
Modifikacija ankete (status aktivnosti ankete)

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#23]
Komponenta:
ModifikacijaAnkete.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Klikom na dugme promjena statusa aktivnosti ne desava se nista, tj. nema nikakve povratne informacije. Promjena nije vidljiva ni na prethodno otvorenoj formi za manipulaciju. Potrebno je zatvoriti formu, pa je opet otvoriti kako bi promjena bila vidljiva.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao administrator”. 
3. Unijeti validne podatke za username i password.
4. Izabrati na meniju Ankete opciju za manipulaciju. Na prikazanoj formi oznaciti neku od anketa, te
klikom na dugme izabrati opciju za njeno modifikovanje.
5. Kliknuti na dugme za promjenu statusa aktivnosti.

**Comment by akadrispahic** [comment]
commit ID:
ed06d4f

Promjenjeno, na klik dugmeta za promjenu statusa aktivnost, promjeni se u textbox-u vrijednost sa otvorene na aktivnu anketu.
