### ISSUE TITLE
Zatvaranje formi

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#24]
Komponenta:
Na svim formama
(ModifikacijaAnkete.java)

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Pri pokretanju neke nove forme, stara ostaje otvorena i to na nacin da je na njoj moguce mijenjati podatke. Tako, istovremeno je moguce biti na vise formi, pa npr. na jednoj obrisati anketu, a na drugoj tu istu modifikovati. Tom prilikom, ispisuje se sljedeci exception:

Prikaz rezultata:
![pokit_fd6b4b8075b32ba75ffe0c9694d2f9af](https://cloud.githubusercontent.com/assets/11391469/7840428/97738696-0497-11e5-9242-5b5d1aa42442.jpg)

Takodjer, zatvaranjem jedne forme, zatvaraju se i sve ostale.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Izabrati opciju “Registrovati se kao administrator”. 
3. Unijeti validne podatke za username i password.
4. Izabrati na meniju Ankete opciju za manipulaciju. Na prikazanoj formi oznaciti neku od anketa, te
klikom na dugme izabrati opciju za njeno modifikovanje, a potom dugme za njeno brisanje.

**Comment by akadrispahic** [comment]
commit ID:
ed06d4f

Ispravljeno, pri odabiru dugmeta Modifikuj, otvara se nova forma, a stara se zatvara
