### ISSUE TITLE
Registracija klijenta

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#25]
Komponenta:
RegistracijaKlijenta.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Prilikom unosa podataka pri popunjavanju forme za unos u slučaju pogrešnog unosa, ispisuju se jedan za drugim 2 MessageBoxa koja javljaju grešku o neispravnom unosu.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Izabrati opciju “Registrovati se kao administrator” 
3. Unijeti validne podatke za username i password
4. Izabrati na meniju Klijenti opciju za dodavanje klijenata.
5. Unijeti u neko od polja za unos neispravan podatak.
6. Kliknuti na dugme za unos.

**Comment by mmujic** [comment]
Commit ID: afb4e9839fe0036f9ddf31d8541c8059fc996c48
