### ISSUE TITLE
Promjena klijenta

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#26]
Komponenta:
PromjenaKlijenta.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Kada se unose podaci za registrovanje klijenta adresa nije obavezan podatak. Medjutim, prilikom izmjene podataka klijenta, klikom na dugme za promjenu, ukoliko adresa nije unesena, dobiva se obavjestenje o tome da mora biti unesena. 

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao korisnik”.
3. Popuniti obavezne podatke u formi za unos, kliknuti na dugme Registruj se.
4. Pokrenuti desktop aplikaciju.
5. Izabrati opciju “Registrovati se kao administrator”. 
4. Izabrati na meniju Klijenti opciju za promjenu klijenata.
5. Kliknuti na dugme promijeni klijenta.

**Comment by mmujic** [comment]
Commit ID: a4e94b263dcba0888161466c8b716470a54f892a
