### ISSUE TITLE
Povratak nazad (button)

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#27]
Komponenta:
odgovaranje.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Prilikom odgovaranja na pitanja ankete nema mogucnosti povratka na prethodno pitanje, iako postoji button nazad, tacnije, klikom na to dugme se ne desava nista.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao korisnik”. 
3. Popuniti obavezne podatke u formi za unos, kliknuti na dugme Registruj se.
4. Izabrati neku od ponudjenih anketa, te poceti sa odgovaranjem pitanja. 
5. Kliknuti na dugme nazad.

**Comment by mmujic** [comment]
Commit ID: ca21eb766d5b4bd68a498281fd585c66cb8005a8
