### ISSUE TITLE
Zavrsetak ankete

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#28]
Komponenta:
odgovaranje.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Odgovaranjem na posljednje pitanje ankete ne zatvara se forma,a ni ne otvara neka druga. 
Cak je moguce drugacije odgovoriti na posljednje pitanje i opet poslati formu. 
Kada se nakon toga ode na statistiku klijenta, ispisu se oba odgovora.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao korisnik”. 
3. Popuniti obavezne podatke u formi za unos, kliknuti na dugme Registruj se.
4. Izabrati neku od ponudjenih anketa, te odgovarati i doci do posljednjeg pitanja.
5. Na posljednjem pitanju upisati ili odabrati odgovor i kliknuti na dugme naprijed.
6. Kliknuti na OK na izbacenom MessageBoxu, a potom opet odgovoriti na posljednje pitanje.
5. Pokrenuti desktop aplikaciju.
6. Izabrati opciju “Registrovati se kao administrator” 
7. Na meniju Statistika odabrati opciju po klijentima.

**Comment by mmujic** [comment]
Commit ID: f3bedb2592aceca87d14970863e57b9d4e594ba0
