### ISSUE TITLE
Validacija OpenTypeQuestion forme

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#29]
Komponenta:
OpenTypeQuestion.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Ukoliko se prilikom popunjavanja ankete u polja predvidjena za pisanje teskta unese nesto drugo,
ne desava se nista, a ne moze se preci ni na sljedece pitanje. Tacnije, ne ispisuje se nista na formama, ali je bacen exception.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao korisnik”. 
3. Popuniti obavezne podatke u formi za unos, kliknuti na dugme Registruj se.
4. Izabrati neku od ponudjenih anketa.
5. U polje za unos teksta pitanja unijeti nesto osim teksta.

**Comment by mmujic** [comment]
Commit ID: f3bedb2592aceca87d14970863e57b9d4e594ba0
