### ISSUE TITLE
Uspjesno popunjen kviz (mbox)

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#30]
Komponenta:
odgovaranje.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Nakon sto korisnik zavrsi sa odgovaranjem pitanja jedne ankete, MessageBox koji se pojavljuje ima naslov 'Registracija klijenta', a ikona koja se pojavljuje uz poruku o uspjesno popunjenoj anketi je ikona koja ukazuje na nastalu gresku.

Prikaz rezultata:
![slikaaaaa](https://cloud.githubusercontent.com/assets/11391469/7840952/f90ac2fa-0499-11e5-85b8-1efa1846544b.jpg)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao korisnik”. 
3. Popuniti obavezne podatke u formi za unos, kliknuti na dugme Registruj se.
4. Izabrati neku od ponudjenih anketa i odgovoriti na sva pitanja.

**Comment by mmujic** [comment]
Commit ID: f3bedb2592aceca87d14970863e57b9d4e594ba0
