### ISSUE TITLE
Zatvaranje ankete

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#31]
Komponenta:
odgovaranje.java

commit ID:
ed06d4f602edb96e9073c1338f66a3442dadcb9a

Opis problema:
Nakon sto korisnik zavrsi sa odgovaranjem pitanja jedne ankete, nema mogucnosti povratka ni na sta, vec mora zatvoriti aplikaciju, pa je opet pokrenuti. Tako, nije moguce da jedan korisnik popuni jednu anketu, pa potom drugu.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju.
2. Izabrati opciju “Registrovati se kao korisnik”. 
3. Popuniti obavezne podatke u formi za unos, kliknuti na dugme Registruj se.
4. Izabrati neku od ponudjenih anketa i odgovoriti na sva pitanja.

**Comment by mmujic** [comment]
Commit ID: 51a0e0e71966241e24b32978df6f09a491c46920
