### ISSUE TITLE
Promjena Passworda, Administrator login

### ISSUE THREAD

**Issue by hcustovic1** [SoftverInzenjeringETFSA/SI2014Tim8#32]
Komponenta:
ba.tim8.kvizbiz.forme Promjena Passworda, Administrator login
commit ID:
b4dd9eb04bcb6d8638369aac15485a061a50e75c
Opis problema:
Ukoliko se u formi za promjenu passworda u administratorskom panelu unesu
afrikati (npr. “ččččč”, password biva prihvaćen. Međutim, ukoliko pokušamo
odraditi login s tim passwordom, dolazi do greške u prijavi.
http://prntscr.com/79qonp
Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Izabrati opciju “Registrovati se kao administrator”
3. Unijeti validne podatke za username I password (generisano od strane
skripteusername:
admin, password:tajna.
4. U meniju izabrati: Profil>
Promjena passworda
5. Kao trenutni password unijeti “tajna”, a za novi “ččččč”.
6. Odjaviti se sa Sistema I pokušati odraditi login sa novim passwordom.

**Comment by JosipKvesic** [comment]
commit 630388a
