### ISSUE TITLE
Promjena klijenta

### ISSUE THREAD

**Issue by hcustovic1** [SoftverInzenjeringETFSA/SI2014Tim8#35]
Komponenta:
ba.tim8.kvizbiz.forme Promjena klijenta
commit ID:
b4dd9eb04bcb6d8638369aac15485a061a50e75c
Opis problema:
Kod promjene klijenta, nije dozvoljen unos slova iz našeg jezika. Također,
datum nije validiran i moguće je unijeti budući datum kao datum prijave.
http://prntscr.com/79qzik
Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Izabrati opciju “Registrovati se kao administrator”
3. Unijeti validne podatke za username I password (generisano od strane
skripteusername:
admin, password:tajna.
4. U meniju izabrati: Klijenti>
Promjena
5. Unijeti riječ koja sadrži slova iz našeg jezika u polja za unos imena ili
prezimena. Unijeti budući datum u polju za unos datuma prijave.

**Comment by ToniMilicevic** [comment]
Datum 7eb8d84790bb1c32fdae35fc0a06b3eee2be193f
Afrikati 7be9cd20361a84b366af87023a6f55b79d6139a5
