### ISSUE TITLE
Dodavanje administratora

### ISSUE THREAD

**Issue by hcustovic1** [SoftverInzenjeringETFSA/SI2014Tim8#36]
Komponenta:
ba.tim8.kvizbiz.forme Dodavanje administratora
commit ID:
b4dd9eb04bcb6d8638369aac15485a061a50e75c
Opis problema:
Kod pokušaja dodavanja novog administratora, validacija nije ispravna za unos
datuma (moguće je unijeti datum iz daleke budućnosti, kao datum rođenja).
Također, moguće je kao password unijeti string koji sadrži karaktere iz našeg
jezika (č, ć, ž, đ, š), koji kasnije neće biti prepoznati prilikom pokušaja
prijave. Još, za unos polja imena I prezimena, neće biti prihvaćeni naši
karakteri I bit će zatražena promjena unosa.
http://prntscr.com/79r5he
http://prntscr.com/79r7tc
Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Izabrati opciju “Registrovati se kao administrator”
3. Unijeti validne podatke za username I password (generisano od strane
skripteusername:
admin, password:tajna.
4. U meniju izabrati: Administratori>
Dodavanje
5. Unijeti riječ koja sadrži slova iz našeg jezika u polja za unos imena ili
prezimena. Unijeti budući datum u polju za unos datuma prijave

**Comment by ToniMilicevic** [comment]
Unos datuma 7eb8d84790bb1c32fdae35fc0a06b3eee2be193f
Afrikati 68c3bb14518506f9c4bd28deec9a78e961279183
