### ISSUE TITLE
Brisanje klijenta

### ISSUE THREAD

**Issue by hcustovic1** [SoftverInzenjeringETFSA/SI2014Tim8#37]
Komponenta:
ba.tim8.kvizbiz.forme Brisanje klijenta
commit ID:
b4dd9eb04bcb6d8638369aac15485a061a50e75c
Opis problema:
Ako pristupimo brisanju klijenta kroz administratorski panel, ništa se ne
dešava, obzirom da dolazi do sljedećeg exceptiona: java.lang.IllegalArgumentException :
node to traverse cannot be null!
http://prntscr.com/79rg2i
Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Izabrati opciju “Registrovati se kao administrator”
3. Unijeti validne podatke za username I password (generisano od strane
skripteusername:
admin, password:tajna.
4. U meniju izabrati: Klijenti>
Brisanje
5. Izabere se klijent iz padajuće liste.
6. Klikne se na button “Obriši klijenta”

**Comment by ToniMilicevic** [comment]
Rijesen problem
Commit
d11388d30bae5c68eb4a58647ebef40f9050d570
