### ISSUE TITLE
Kviz bez pitanja - izuzetak

### ISSUE THREAD

**Issue by hcustovic1** [SoftverInzenjeringETFSA/SI2014Tim8#38]
Komponenta:
ba.tim8.kvizbiz.forme PočetnaKlijentZaKlijenta
commit ID:
b4dd9eb04bcb6d8638369aac15485a061a50e75c
Opis problema:
Ako u bazi postoji kviz koji je bez pitanja, on će biti prikazan na formi I
ukoliko ga korisnik izabere doći će dobacanja izuzetka:
Exception in thread "AWTEventQueue0"
java.lang.IndexOutOfBoundsException : Index: 0, Size: 0
http://prntscr.com/79rma5
Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Izabrati opciju “Registrovati se kao korisnik”
3. Unijeti validne podatke za username I password
4. Izabrati kviz, za koji nisu definirana pitanja

**Comment by FarukLjuca** [comment]
Iako se exception desava na ovoj formi, on je bacen u formi odgovaranje.java, tako da Muhamede, ovo je tvoj Issue.

**Comment by mmujic** [comment]
OK

**Comment by mmujic** [comment]
Commit ID: 45e649bc1ef9c65b38927baa19273dacb8fdb9c6
