### ISSUE TITLE
Promjena veličine prozora

### ISSUE THREAD

**Issue by hcustovic1** [SoftverInzenjeringETFSA/SI2014Tim8#39]
Komponenta:
ba.tim8.kvizbiz.forme Dodavanje administratora, Brisanje administratora, Promjena klijenta, Brisanje klijenta, Manipulacija anketama, 
commit ID:
b4dd9eb04bcb6d8638369aac15485a061a50e75c
Opis problema:
Prilikom maksimizacije i općenito mijenjanja veličine prozora navedenih formi ne dolazi do srazmjernih promjena veličina korištenih komponenti.
http://prntscr.com/7a2ndz
Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Izabrati opciju “Registrovati se kao administrator”
3. Unijeti validne podatke za korisničko ime i password
4. U meniju izabrati Administrator->Dodavanje, Administrator->Brisanje, Klijenti->Promjena, Klijenti->Brisanje, Ankete->Manipulacija
5. Maksimizirati prozor forme

**Comment by ToniMilicevic** [comment]
commit
440caa30bcfb9cedc29f19d8e1306374a155bcee
