### ISSUE TITLE
Pozicija formi na ekranu

### ISSUE THREAD

**Issue by hcustovic1** [SoftverInzenjeringETFSA/SI2014Tim8#40]
-Komponenta:
ba.tim8.kvizbiz.forme Sve forme

-commit ID: b4dd9eb04bcb6d8638369aac15485a061a50e75c

-Opis problema:
Nakon pokretanja aplikacije, forme se ne prikazuju na centru ekrana, već u gornjem lijevom uglu.
http://prntscr.com/7a2qhe

-Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju

**Comment by ToniMilicevic** [comment]
commit
440caa30bcfb9cedc29f19d8e1306374a155bcee
