### ISSUE TITLE
Klijent forma - vidljive administratorske opcije

### ISSUE THREAD

**Issue by hcustovic1** [SoftverInzenjeringETFSA/SI2014Tim8#41]
-Komponenta: ba.tim8.kvizbiz.forme PocetnaKlijentZaKlijenta

-commit ID: b4dd9eb04bcb6d8638369aac15485a061a50e75c

-Opis problema:
Ukoliko se kroz registrujemo kao administrator, a zatim odradimo logout, i prijavimo se kao korisnik, na korisničkoj formi ostaje meni sa administratorskim opcijama (dodavanje,brisanje,modifikovanje administratora, klijenata, anketa,…)
http://prntscr.com/7a2vvt

-Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Izabrati registraciju kao administrator, te unijeti validne username i password
3. Odraditi logout
4. Registrovati se kao korisnik

**Comment by FarukLjuca** [comment]
Zaboravio bio na logout staviti usernameLogiranogAdmina = null; XD
