### ISSUE TITLE
Promjena ličnih podataka : Ime i Prezime

### ISSUE THREAD

**Issue by CodeBobomb** [SoftverInzenjeringETFSA/SI2014Tim8#48]
Komponenta: 
Promjenalicnihpodataka.java

commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim8/commit/54e871e3be7e917f0b94a8b0983654886b28056c

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Ulogovati se kao administrator
3. Na Navigacijskoj traci otvoriti Profil i izabrati "Promjena ličnih podataka"
4. U polje Ime unijeti string: "A"
5. U polje Prezime unijesti string: "B"
6. Kliknuti dugme "Promjeni lične podatke"
7. Kliknuti dugme "Yes"

Dobijeni rezultat:
- Uspiješno se spasi adminsitrator sa nevalidnim (prekratkim) imenom i prezimenom

Očekivani rezultat:
- Upozorenje da je uneseno ime i prezime prekratko

**Comment by ToniMilicevic** [comment]
Napravljena je validacija, a ko onemogucava ponosne mame i tate da daju ime dijetetu po abecedi, prvo dijete A, drugo dijete B, trece dijete C, itd.

**Comment by JosipKvesic** [comment]
Ispravili smo.Ime treba imati minimalno 2 slova (npr. Ed), a prezime 3 ( npr Mak). 9f990f2
