### ISSUE TITLE
Registracija klijenta: Ime Prezime

### ISSUE THREAD

**Issue by CodeBobomb** [SoftverInzenjeringETFSA/SI2014Tim8#49]
Komponenta: Registracijaklijenta.java

commit ID:
https://github.com/SoftverInzenjeringETFSA/SI2014Tim8/commit/54e871e3be7e917f0b94a8b0983654886b28056c

Koraci za reprodukciju problema:
1. Pokrenuti aplikaciju kvizbiz
2. Odabrati "Registruj se kao korisnik"
3. U polje ime i prezime unijeti : Ćamil Sijarić
4. U ostala polja unijeti validne podatke
5. Kliknuti dugme "Registruj se"

Dobijeni rezultat:
-Poruka da Ime i Prezime sadrži nevalidne karaktere

Očekivani rezultat:
-Uspješna kreacija korisnika

**Comment by ToniMilicevic** [comment]
commit
630388ae5c81f6d95660113121ab4af982fa98dd
