### ISSUE TITLE
Promjena passworda

### ISSUE THREAD

**Issue by CodeBobomb** [SoftverInzenjeringETFSA/SI2014Tim8#50]
Komponenta:
Promjenapassworda.java

Commit:
https://github.com/SoftverInzenjeringETFSA/SI2014Tim8/commit/54e871e3be7e917f0b94a8b0983654886b28056c

Koraci za reprodukciju problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Ulogovati se kao administrator
3. Na navigacijskoj traci odabrati Profil
4. Kliknuti na Promjenu passworda
5. Unijeti trenutni password
6. Unijeti string "a" u novi password i ponovljeni novi password
7. Kliknuti na dugme Promjeni password

Dobijeni rezultat:
- Uspješno promjena passworda

Očekivani rezutat:
- Opomena da je password prekratak

**Comment by JosipKvesic** [comment]
commit 9f990f2
