### ISSUE TITLE
Anketa: Dodavanje pitanja

### ISSUE THREAD

**Issue by CodeBobomb** [SoftverInzenjeringETFSA/SI2014Tim8#51]
Komponenta: DodavanjeManipulacija.java

commit ID:
https://github.com/SoftverInzenjeringETFSA/SI2014Tim8/commit/54e871e3be7e917f0b94a8b0983654886b28056c

Koraci za reprodukciju problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Ulogovati se kao administrator
3. Na navigacijskoj traci izabrati Anketa
4. Kliknuti na Dodavanje u padajućem meniju
5. Unijeti naslov Ankete ("TestAnketa")
6. Kliknuti na Dodaj novo pitanje dugme
7. Odabrati neku kategoriju (svejedno)
8. Kliknuti Ok

Dobijeni rezultat:
-Poruka o uspješnom dodavanju pitanja

Očekivani rezultat:
-Poruka da nije dozvoljeno pitanje bez teksta

**Comment by FarukLjuca** [comment]
Isto kao issue #34.
