### ISSUE TITLE
Korisnik: Početni ekran

### ISSUE THREAD

**Issue by CodeBobomb** [SoftverInzenjeringETFSA/SI2014Tim8#52]
Komponenta: Pocetnaklijent.java

commit ID:
https://github.com/SoftverInzenjeringETFSA/SI2014Tim8/commit/54e871e3be7e917f0b94a8b0983654886b28056c

Koraci za reprodukciju problema:
1. Otvoriti aplikaciju Kvizbiz
2. Ulogovati se kao adminsitrator
3. Na navigacijskoj traci odabrati Profil
4. Odbrati "Odjava" izbor
5. Kliknuti na dugme "Registruj se kao korisnik"
6. Unijeti validne podatke i kliknuti dugme "Registruj se"

Dobijeni rezultat:
- Početni ekran sa prikazanom navigacijskom trakom prethodno logovanog administratora (i pristup njegovim podacima)

Očekivani rezultat:
- Početni  ekran za korisnike

**Comment by FarukLjuca** [comment]
Isto kao issue #41.
