### ISSUE TITLE
Brisanje administratora

### ISSUE THREAD

**Issue by elvinva** [SoftverInzenjeringETFSA/SI2014Tim8#53]
Komponenta: 
BrisanjeAdministratora.java

commit ID:
54e871e

Opis problema: 
Omogućeno je brisanje administratora koji je već prijavljen i nakon brisanja i dalje ostaje prijavljen, što javlja problem ukoliko se ide na njegov već obrisani profil.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Ulogovati se kao administrator
3. Na navigacijskoj traci odabrati Administrator
4. Kliknuti na Brisanje
5. U polje izaberite administratora uzabrati onog koji je već prijavljen
6. Kliknuti na Obriši administratora
7. Kliknuti na dugme Promjeni password

Dobijeni rezultat:
Administrator je uspješno obrisan! i i dalje se aplikacija ponasa kao jos postoji

Očekivani rezutat:
Nakon brisanja odjava sa profila ili da se onemogući brisanje već prijavljenog administratora

**Comment by ToniMilicevic** [comment]
ne moze se admin sam sebe pobrisati
commit
157943cffedf17f10d77e7d9bb254e98049d6086
