### ISSUE TITLE
Prikaz slova Č, Ć i Đ kao upitnika

### ISSUE THREAD

**Issue by elvinva** [SoftverInzenjeringETFSA/SI2014Tim8#55]
Komponenta:
DodavanjeAdministratora.java / PregledAdministratora.java

Commit ID:
54e871e

Opis problema:
Bosanska slova Č, Ć i Đ se prikazuju kao upitnici

Koraci za reproduciranje problema:
Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Ulogovati se kao administrator
3. Na navigacijskoj traci odabrati Administrator
4. Kliknuti na Dodavanje
5. Unijeti npr. Username gdje ima Č, Ć ili Đ npr. Ćato
6. Na navigacijskoj traci odabrati Administrator
7. Kliknuti na Pregled

Dobijeni rezultat:
Prikaz username administratora kao ?ato

Očekivani rezultat:
Očekuje se korektan prikaz slova tj. Č Ć Ž Đ (Ćato)

**Comment by ToniMilicevic** [comment]
Commit
630388ae5c81f6d95660113121ab4af982fa98dd
