### ISSUE TITLE
Brisanje administratora bez upozorenja(koje je navedeno u SRS-u)

### ISSUE THREAD

**Issue by elvinva** [SoftverInzenjeringETFSA/SI2014Tim8#56]
Komponenta: 
BrisanjeAdministratora.java

commit ID:
54e871e

Opis problema: 
Nakon brisanja administratora javlja se poruka: Administrator je uspješno obrisan! bez da se korisnik pita je li korisnik to zaista želi a što je navedeno u SRS-u u funkcionalnom zahtjevu 3.2.4.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Ulogovati se kao administrator
3. Na navigacijskoj traci odabrati Administrator
4. Kliknuti na Brisanje
5. U polje izaberite administratora izabrati nekog administratora
6. Kliknuti na Obriši administratora

Dobijeni rezultat:
poruka Administrator je uspješno obrisan! bez upozorenja koje je navedeno u SRS 3.2.4.

Očekivani rezutat:
Nakon klika na Obriši administratora izbacuje se pitanje je li korisnik siguran da to želi

**Comment by ToniMilicevic** [comment]
Ostavilo se dovoljno vremena i prostora da administrator razmisli da li zaista zeli izbrisati administratora

**Comment by elvinva** [comment]
"Sistem pokreće procedure za brisanje uz prethodnu provjeru u vidu pitanja da li korisnik zaista želi da izbriše korisnički račun" ovo je ono što je navedeno u Vašem SRS-u, a nije implementirano.

**Comment by ToniMilicevic** [comment]
commit
157943cffedf17f10d77e7d9bb254e98049d6086
