### ISSUE TITLE
Modifikacija klijenta 

### ISSUE THREAD

**Issue by elvinva** [SoftverInzenjeringETFSA/SI2014Tim8#58]
Komponenta: 
PromjenaKlijenta.java

commit ID:
54e871e

Opis problema: 
Moguće je promjeniti ime,prezime,jmbg,datum rođenja te spol klijenta iako je to u SRS-u u funkcionalnom zahtjevu 3.2.7. pod uslovima validnosti zabranjeno!

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Ulogovati se kao administrator
3. Na navigacijskoj traci odabrati Klijenti
4. Kliknuti na Promjena
5. Odabrati nekog klijenta
6. Unijeti drugacije ime ili prezime ili jmbg ili datum rodjenja ili spol 
7. Kliknuti na dugme Promjeni klijenta

Dobijeni rezultat:
Poruka: Klijent je uspješno promjenjen

Očekivani rezutat:
Poruka da nije dozvoljena promjena tih podataka, kako je i navedeno u SRS-u u poglavlju 3.2.7.

**Comment by ToniMilicevic** [comment]
Commit
630388ae5c81f6d95660113121ab4af982fa98dd
