### ISSUE TITLE
Pretraga i pregled klijenata abecedni prikaz

### ISSUE THREAD

**Issue by elvinva** [SoftverInzenjeringETFSA/SI2014Tim8#59]
Komponenta: 
PregledKlijentav1.java

commit ID:
54e871e

Opis problema: 
Klijenti se ne prikazuju po abecednom redosljednu kako je navedeno u SRS-u u funkcionalnom zahtjevu 3.2.9., nego po redosljednu kojim su dadani.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Ulogovati se kao administrator
3. Na navigacijskoj traci odabrati Klijenti
4. Kliknuti na Pregled

Dobijeni rezultat:
Klijenti su prikazani u tabeli po redosljedu kako su dodani, a ne po abecednom redosljedu kako je navedeno u SRS-u u funkcionalnom zahtjevu 3.2.9.

Očekivani rezutat:
Da su klijenti prikazani u tabeli po abecednom redosljedu kako je i navedeno u SRS-u 3.2.9.

**Comment by oljubuncic1** [comment]
Klijenti se prikazuju abecedno po prezimenu.
