### ISSUE TITLE
Kreiranje nove ankete, naziv nije jedinstven

### ISSUE THREAD

**Issue by elvinva** [SoftverInzenjeringETFSA/SI2014Tim8#60]
Komponenta: 
KreiranjeAnkete.java

commit ID:
54e871e

Opis problema: 
Moguće je kreirati dvije ankete sa potpuno istim nazivom iako je u SRS-u u funkcionalnom zahtjevu 3.2.10. navedeno da Naziv ankete mora biti jedinstven u cijelom sistemu 
![image](https://cloud.githubusercontent.com/assets/6854455/7891654/b270fb50-064e-11e5-8be1-ce4d0f200e5e.png) na slici se vide dvije ankete sa istim nazivom

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Ulogovati se kao administrator
3. Na navigacijskoj traci odabrati Ankete
4. Kliknuti na Dodavanje
5. Odabrati nekog klijenta
6. Unijeti naziv ankete koji već postoji

Dobijeni rezultat:
Potvrda o uspješnom kreiranju

Očekivani rezutat:
Upozorenje da anketa sa tim nazivom već postoji

**Comment by FarukLjuca** [comment]
Issue #21 je isti.
