### ISSUE TITLE
Pogresan unos datuma za Registraciju korisnika

### ISSUE THREAD

**Issue by unReaLaneS** [SoftverInzenjeringETFSA/SI2014Tim8#61]
Komponenta:
RegistracijaKlijenta.java

commit ID:
630388ae5c81f6d95660113121ab4af982fa98dd

Opis problema:
Unos pogresnog datuma se prihvata kao datum i dodaje se klijent u bazu.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Kliknuti na dugme "Registruj se kao korisnik".
3. Unijeti sve ostale podatke ispravno, osim polja Datum rodjenja.
4. U polje datum rodjenja unijeti datum: "1992-11-31".

Dobijeni rezultat:
- Potvrda o uspješnom kreiranju. U bazu je ubacen datum "1992-12-01".

Očekivani rezultat:
- Očekuje se upozoravajuca poruka ili MessageBox sa izrazom da je to nepostojeci datum.

**Comment by ToniMilicevic** [comment]
Zatvoren
