### ISSUE TITLE
Promjena licnih podataka administratora

### ISSUE THREAD

**Issue by unReaLaneS** [SoftverInzenjeringETFSA/SI2014Tim8#62]
Komponenta:
PromjenaLicnihPodataka.java

commit ID:
630388a

Opis problema:
Promijene se podaci, iako se klikne na dugme "Promijeni Licnih podatke", pa se izabere opcija Ne.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Kliknuti na dugme "Prijavi se kao administrator".
3. Unijeti podatke za username i password admina.
4. Kliknuti na Profil -> Promjena licnih podataka.
5. Promijeniti podatke npr. email.
6. Kliknuti na dugme Promijeni licnih podatke.
7. Pojaviti ce se MessageBox, sa pitanjem da li smo sigurni da zelimo promijeniti.
8. Tu izabrati opciju Ne.

Dobijeni rezultat:

```
Podaci u bazi podataka su promijenjeni.
```

Očekivani rezultat:

```
Podaci se ne bi smijeli promijeniti, jer smo izabrali opciju Ne.
```

**Comment by JosipKvesic** [comment]
625554a
