### ISSUE TITLE
Nepostojanje polja JMBG za Klijente

### ISSUE THREAD

**Issue by unReaLaneS** [SoftverInzenjeringETFSA/SI2014Tim8#63]
Komponenta:
RegistracijaKlijenta.java

commit ID:
630388a

Opis problema:

Ocekivano je da se na formi RegistracijaKlijenta nalazi polje JMBG kako je navedeno u funkcionalnom zahtjevu "3.2.21 Unos ličnih podataka klijenta".

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz.
2. Kliknuti na dugme "Registruj se kao korisnik".
3. Polje JMBG ne postoji.

**Comment by oljubuncic1** [comment]
Kolega,

mislim da gledate pogrešnu verziju SRS-a. Zadnja verzija SRS-a je SRSverzija2 u kojoj se unutar zahtjeva 3.2.21 ne nalazi JMBG.
