### ISSUE TITLE
Nemogucnost zavrsetka kviza i upis odgovora kao praznih stringova u bazu

### ISSUE THREAD

**Issue by unReaLaneS** [SoftverInzenjeringETFSA/SI2014Tim8#65]
Komponenta:
odgovaranje.java

commit ID:
630388a

Opis problema:
Pokrene se kviz, na pitanja se ne odgovara, nego se samo klikce na dugme "Naprijed".
Kad se dodje do zadnjeg pitanja, nije mogu ici ni naprijed ni nazad, zaglavimo na toj formi.
Nije moguce dalje kretanje kroz program.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju KvizBiz.
2. Izabrati opciju “Registrovati se kao korisnik”.
3. Unijeti validne podatke.
4. Izabrati kviz "Druga anketa".
5. Kviz se pokrene.
6. Ici na dugme Naprijed, sve do kraja kviza, bez odgovaranja na pitanja.

Dobijeni rezultat:
Kviz stane na zadnjem pitanju, te je nemoguce vise kretanje ni naprijed ni nazad.
U bazi na mjestima odgovora stavljaju se prazni stringovi kao odgovori.

Očekivani rezutat:
Obavijest da nisu pitanja odgovorena.

**Comment by FarukLjuca** [comment]
Isto kao issue #28.
