### ISSUE TITLE
Brisanje Klijenata sa istim imenom i prezimenom

### ISSUE THREAD

**Issue by unReaLaneS** [SoftverInzenjeringETFSA/SI2014Tim8#66]
Komponenta:
BrisanjeKlijenta.java

commit ID:
630388a

Opis problema:
Ako napravimo 2 klijenta sa istim imenima i prezimenima, a ostale podatke stavimo razlicite.
Kada zelimo da brisemo klijenta u formi Brisanje klijenta, u combobox-u "Izaberite klijenta:" se prikazu
oba klijenta, ali su ta oba klijenta ustvari samo zadnji dodani klijent. Kojeg god da izaberemo 
ustvari izabrali smo zadnjeg, i ako kliknemo na dugme Obrisi klijenta ustvari brisemo samo zadnjeg.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju KvizBiz.
2. Izabrati opciju “Registrovati se kao korisnik”.
3. Unijeti validne podatke.
4. Izaci iz aplikacije.
5. Pokrenuti aplikaciju i izabrati opciju “Registrovati se kao korisnik”.
6. Unijeti ime i prezime kao kod proslog klijenta, ali ostale podatke razlicite.
7. Izaci iz aplikacije
8. Ulogovati se kao admin.
9. Izabrati Klijenti, pa onda Brisanje.
10. U combobox-u izabrati prvog klijenta od 2 dodana.
11.Pogledati podatke ispod.
12.U combobox-u izabrati drugog klijenta od 2 dodana.
13.Pogledati podatke.
14. Podaci su isti za oba izabrana.
15. Izabrati bilo kojeg klijenta od ova dva i kliknuti na dugme Obrisi klijenta.

Dobijeni rezultat:
Obrisan je zadnji dodani klijent, kojeg god da smo od ta dva klijenta izabrali i kliknuli na dugme Obrisi klijenta. Isto tako kojeg god od ta dva klijenta da smo izabrali u combobox-u, ustvari je izabran samo zadnji dodani klijent u bazu.

Očekivani rezutat:

Ako izaberem prvog klijenta, treba prvi da se izbrise, ako izaberemo drugog, treba drugi da se izbrise. Iako imaju isto ime i prezime, ali oni su razliciti klijenti.

**Comment by ToniMilicevic** [comment]
commit
5614bb3d866306891d4956df4821395aa173de46
