### ISSUE TITLE
Pregled anketa, abecedni prikaz

### ISSUE THREAD

**Issue by elvinva** [SoftverInzenjeringETFSA/SI2014Tim8#67]
Komponenta: 
ManipulacijaAnketama.java

commit ID:
6fe25b1

Opis problema: 
Ankete se ne prikazuju po abecednom redosljednu kako je navedeno u SRS-u u funkcionalnom zahtjevu 3.2.14., nego po redosljednu kojim su dadani. 
![image](https://cloud.githubusercontent.com/assets/6854455/7897444/94fe228a-06dc-11e5-9457-4ce0969375aa.png)

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Ulogovati se kao administrator
3. Na navigacijskoj traci odabrati Ankete
4. Kliknuti na Pregled

Dobijeni rezultat:
Ankete su prikazani u tabeli po redosljedu kako su dodani, a ne po abecednom redosljedu kako je navedeno u SRS-u u funkcionalnom zahtjevu 3.2.14.

Očekivani rezutat:
Da su ankete prikazani u tabeli po abecednom redosljedu kako je i navedeno u SRS-u

**Comment by akadrispahic** [comment]
commit ID:
6fe25b1

ispravljeno
