### ISSUE TITLE
UIS- nesuglašenost forme za modifikaciju anketa sa implementiranim

### ISSUE THREAD

**Issue by elvinva** [SoftverInzenjeringETFSA/SI2014Tim8#69]
Komponenta: 
ManipulacijaAnketama.java

commit ID:
6fe25b1

Opis problema: 
Implementirana forma Manipulacijama anketama ne odgovara onoj specificiranoj u UIS dokumentu, nedostaju buttoni Pregledaj označenu i otkaži. Također tabela nije usaglašena.
implementirana forma: 
![image](https://cloud.githubusercontent.com/assets/6854455/7897680/9a1114fa-06e4-11e5-8955-676445e6f2c4.png)
specificirana forma u UIS-u: 
![image](https://cloud.githubusercontent.com/assets/6854455/7897681/b1e55b72-06e4-11e5-8f2f-154612c2a9b3.png)

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Ulogovati se kao administrator
3. Na navigacijskoj traci odabrati Ankete
4. Kliknuti na Manipulacija

Dobijeni rezultat: Forma kao na prvoj slici

Očekivani rezultat: Usklađena forma sa UIS-om

**Comment by akadrispahic** [comment]
commit ID:
6fe25b1

Ima i pregled, i arhiviranje
