### ISSUE TITLE
Nema poruke upozorenja kada se unese besmislen datum tj godina

### ISSUE THREAD

**Issue by ilmakurtovic** [SoftverInzenjeringETFSA/SI2014Tim8#71]
Komponenta:
RegistracijaKlijenta.java

commit ID:
630388:

Opis:
Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju Kvizbiz
2. Kliknuti na dugme "Registruj se kao korisnik".
3. Unijeti sve ostale podatke ispravno, osim polja Datum rodjenja.
4. U polje datum rodjenja unijeti datum: "1901-5-1". (http://prntscr.com/7b44xg)

Dobijeni rezultat:
Potvrda o uspješnom kreiranju, korisnik dodan u bazu.

Očekivani rezultat:

Očekuje se upozoravajuca poruka.

**Comment by FarukLjuca** [comment]
A šta ako se pojavi potreba da se "prepiše" neka anketa koja je rađena u prošlosti sa klijentom koji se baš rodio 1901.?

**Comment by ilmakurtovic** [comment]
Hoćeš li ukoliko se pojavi takva potreba pokrenuti svoju aplikaciju i registrovati se kao taj klijent koji je tada rođen?
