### ISSUE TITLE
Buttoni za kviz su veci od slike na buttonima

### ISSUE THREAD

**Issue by unReaLaneS** [SoftverInzenjeringETFSA/SI2014Tim8#72]
Komponenta:
PocetnaKlijentZaKlijenta.java

commit ID:
b8a17e9efaa408c4cf1653d69e2396db02eb060a

Opis problema:
Ako kliknemo pokraj ikone kviza, kviz se opet pokrene.
Jer su buttoni za pokretanje kviza veci od slike na buttonu.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju KvizBiz.
2. Izabrati opciju “Registrovati se kao korisnik”.
3. Unijeti validne podatke.
4. Izaci iz aplikacije.
5. Pomjeriti mis malo pored ikone kviza i kviz ce se pokrenuti.

Dobijeni rezultat:

Poruka sa tekstom, da li zelimo odabrati taj kviz.

Očekivani rezutat:
MessageBox sa tekstom da li zelimo odabrati taj kviz se ne bi trebala pojaviti.

**Comment by FarukLjuca** [comment]
To je uvedeno kako bi korisniku bilo lakše pokrenuti kviz (ne mora biti 100% precizan)
