### ISSUE TITLE
Brisanje anketa

### ISSUE THREAD

**Issue by unReaLaneS** [SoftverInzenjeringETFSA/SI2014Tim8#73]
Komponenta:
ManipulacijaAnketama.java

commit ID:
b8a17e9efaa408c4cf1653d69e2396db02eb060a

Opis problema:
Kada izbrisemo oznacenu anketu u formi Manipulacija Anketama, otvara se nova forma Manipulacija Anketama, a stara je i dalje otvorena. Zatim kliknom na X bilo koje od otvorenih formi, gase se sve forme.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju KvizBiz.
2. Ulogovati se kao administrator.
3. Izabrati Ankete->Manipulacija.
4. Selektovati neku od anketa.
5. Kliknuti da dugme Obrisi oznacenu

Dobijeni rezultat:

Anketa je izbrisana u novoj formi, ali je stara forma i dalje otvorena. Tako u slucaju da brisemo 10 anketa imali bi 10 formi otvorenih.

Očekivani rezutat:
Anketa se izbrise i otvori se nova forma sa tacnim brojem anketa, a stara se forma zatvori.

**Comment by FarukLjuca** [comment]
Isto kao ussue #24

**Comment by unReaLaneS** [comment]
Nije isto, kod nje kada otvori Modifikovanje ankete otvori se nova forma, ali na staroj brise anketu i ne otvara se nova forma kada brise.
U mom slucaju odmah kada selektujemo anketu i kliknemo da se brise otvaraju se 2 forme, te je na jednoj obrisana anketa, a na drugoj nije.

**Comment by FarukLjuca** [comment]
Skinuo sam verziju commit-a u kojem ste naveli da ste dobili neispravno ponašanje aplikacije (označavanje ankete i klik na obriši) i ne otvara se novi prozor, molim vas provjerite da li su koraci za reproduciranje problema ispravni (možda ste nešto prije radili što je uzrokovalo problem, navedite i to) :smiley:

**Comment by unReaLaneS** [comment]
Evo pokusavam vec 1 sat da to ponovim ne moze, ne znam ni ja kako sam ono uspio. Mislim kada sam kliknuo na obrisi iskocile bi 2 forme, ali ne znam nikako sta sam prije toga radio. Tako nema veze neka ostane Invalid :D
