### ISSUE TITLE
Manipulacija anketama, klik na dugme OK!

### ISSUE THREAD

**Issue by unReaLaneS** [SoftverInzenjeringETFSA/SI2014Tim8#74]
Komponenta:
ManipulacijaAnketama.java

commit ID:
1bacccc61a67477813e20921a72817af06b1ccfb

Opis problema:

Klikom na dugme OK! na formi Manipulacija Anketama, mozemo otvoriti koliko hocemo formi naziva Pregled anketa.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju KvizBiz.
2. Ulogovati se kao administrator.
3. Izabrati Ankete->Manipulacija.
4. Kliknuti da dugme OK! zeljeni broj puta.

Dobijeni rezultat:

Otvara se nova forma, a stara forma ili stare forme se ne zatvaraju.

Očekivani rezutat:
Otvaranje forme Pregled anketa, a stara forma Manipulacija Anketama se zatvara.

**Comment by akadrispahic** [comment]
commit ID:
1bacccc

Ispravljeno
