### ISSUE TITLE
Greske u pisanju

### ISSUE THREAD

**Issue by CSharpQueen** [SoftverInzenjeringETFSA/SI2014Tim8#75]
Komponenta:
Pregled Anketa
Dodavanje Ankete
Promjena passworda

commit ID:
157943cffedf17f10d77e7d9bb254e98049d6086

Opis problema:
Greške u nazivima labela.

Neke od uocenih gresaka prikazane su na sljedecim slikama:

Odaberie ID:
![greska nova 1](https://cloud.githubusercontent.com/assets/11391469/7898776/5702358c-070b-11e5-8d55-b1671bb2091d.jpg)

Nalov ankete:
![greska nova 2](https://cloud.githubusercontent.com/assets/11391469/7898777/5f57825a-070b-11e5-9ec9-c8c1d0834d09.jpg)

Pored navedenih, susrecu se jos i promjeni/promijeni i slicno

Koraci za reproduciranje problema(prve od navedenih gresaka):
1. Pokrenuti desktop aplikaciju
2. Izabrati opciju “Registrovati se kao administrator” 
3. Odabrati meni Ankete, a potom opciju Pregled.

U slucaju ostalih gresaka, izmijeniti korak 3, a potom odabrati opciju Dodavanje na istom meniju.

**Comment by akadrispahic** [comment]
commit ID:
157943c

Ispravljene greške
