### ISSUE TITLE
Onemogućen unos dva imena prilikom dodavanja novog administratora

### ISSUE THREAD

**Issue by ilmakurtovic** [SoftverInzenjeringETFSA/SI2014Tim8#77]
Komponenta:
DodavanjeAdministratora

commit ID:
630388

Opis problema:

Nije uradjena korektna validacija podataka, pa je tako onemogucen unos dva imena prilikom dodavanja administratora.  

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Izabrati opciju “Prijaviti se kao administrator” 
3. Unijeti validne podatke za username i password
4. Izabrati opciju za dodavanje administratora
5. Prilikom upisivanja imena, nije dozvoljen unos space-a, pa se tako npr ne mogu unijeti dva imena

Dobijeni rezultat:

Onemogućen unos dva imena.

Očekivani rezultat:

Omogućen unos dva imena.

**Comment by ToniMilicevic** [comment]
commit 
5614bb3d866306891d4956df4821395aa173de46
