### ISSUE TITLE
Forma DodavanjeAdministratora se ne prilagodi veličini ekrana

### ISSUE THREAD

**Issue by ilmakurtovic** [SoftverInzenjeringETFSA/SI2014Tim8#79]
Komponenta:
DodavanjeAdministratora

commit ID:
630388

Opis problema:

Prilikom povećavanja forme ista se ne prilagodi veličini ekrana.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Logovati se
3. Izabrati meni Administratori i na njemu opcija dodavanje

Dobijeni rezultat:
http://pokit.org/get/?fbc1604e6283e66fc4f31825f6372302.jpg

Očekivani rezultat:
Prilagođena forma.

**Comment by ToniMilicevic** [comment]
commit
440caa3
