### ISSUE TITLE
Forma PromjenaKlijenta se ne prilagodi veličini ekrana

### ISSUE THREAD

**Issue by ilmakurtovic** [SoftverInzenjeringETFSA/SI2014Tim8#80]
Komponenta:
PromjenaKlijenta

commit ID:
630388

Opis problema:

Prilikom povećavanja forme ista se ne prilagodi veličini ekrana.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju
2. Logovati se
3. Izabrati meni Klijenti i na njemu promjenaklijenta

Dobijeni rezultat:
http://pokit.org/get/?7330291d0dce9ebfa3c36b337c26e609.jpg

Očekivani rezultat:
Prilagođena forma.

**Comment by ToniMilicevic** [comment]
commit
440caa3
